### ISSUE TITLE
Improve FilterByValueBlock invalid value error handling

### ISSUE THREAD

**Issue by markmc** [instructlab/sdg#133]
In #110 we see:

```
    self.operation(x[self.column_name], value) for value in self.value
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'NoneType' and 'float'
```

The issue here is that `convert_dtype` couldn't handle the value in the column, so we set it to None. And then `operator.ge` can't handle None

If conversion fails, it's not straightforward to pick a default value - it needs to be the same type as `convert_dtype` and it should also (presumably) fail to pass the filter operator

Proposal:

1. Add a `default_value` field - this is the value that will be used if `convert_dtype()` fails
2. We will define a default `default_value` for each supported `convert_dtype` - `float` and `int` would be zero, and `bool` would be `False

e.g. 
```
block_type: FilterByValueBlock
   block_config:
     block_name: filter_questions
     filter_column: score
     filter_value: 1.0
     operation: eq
     convert_dtype: float
     default_value: 0
```

We would also be able to resolve #123 with this approach - i.e. re-enable multi-processing for the type conversion
