### ISSUE TITLE
Support a "blank" model prompt in `LLMBlock`

### ISSUE THREAD

**Issue by markmc** [instructlab/sdg#136]
See aakankshaduggal/sdg#5

In order to support custom pipeline use cases where the pipeline author wishes to completely control the contents of the model prompt, we need some way of allowing the pipeline author to request a "blank template"

The POC was:

```
_BLANK_PROMPT = "{prompt}"

_MODEL_PROMPTS = {
    MODEL_FAMILY_MIXTRAL: _MODEL_PROMPT_MIXTRAL,
    MODEL_FAMILY_MERLINITE: _MODEL_PROMPT_MERLINITE,
    MODEL_FAMILY_BLANK: _BLANK_PROMPT
}
```

Put more simply, we want a pipeline author to be able to bypass the `model_prompt` here:

```
        prompts = [
            self.model_prompt.format(prompt=self._format_prompt(sample))
            for sample in samples
	]
```

How about `model_family: none` ?

```
  - name: custom_block
    type: LLMBlock
    config:
      config_path: ../../configs/knowledge/custom_config.yaml
      model_family: none
      gen_kwargs:
          model_id: custom_model
```

**Comment by xukai92** [comment]
I believe directly defining it at the prompt template level is better than coupling it with model family: I could have a model with Mixtral architecture but finetuned to use another prompt template. 
In this case do we really want to label the Mixtral model as a different model family? 
Although this is okay for the current codebase as it's the only place where model family got used, but it doesn't sound right. 
Besides in the future if we will need to use model family for any architecture related thing we will meet problem.

**Comment by markmc** [comment]
Yeah, you're right

So a `model_prompt` field which is a template uses `{prompt}`

```
  - name: custom_block
    type: LLMBlock
    config:
      config_path: ../../configs/knowledge/custom_config.yaml
      model_family: "FOO {prompt} BAR"
      gen_kwargs:
          model_id: custom_model
```

and also support `model_prompt: none` or similar
