### ISSUE TITLE
`block.gen_kwargs` should move to `llmblock.config.gen_kwargs`

### ISSUE THREAD

**Issue by markmc** [instructlab/sdg#138]
Reviewing the schema in #132, I see that we allow `gen_kwargs` with any block type

However,  `gen_kwargs` is specific to `LLMBlock` - it's basically arguments based to `completions.create()`

Right now it's at the top-level and pass to `generate()`

```
  - name: gen_contexts
    type: LLMBlock
    config:
      config_path: ../../configs/skills/contexts.yaml
      output_cols:
        - context
    gen_kwargs:
      temperature: 0.7
      max_tokens: 2048
      n: 10
```

but it should move into `block.config`

```
  - name: gen_contexts
    type: LLMBlock
    config:
      config_path: ../../configs/skills/contexts.yaml
      output_cols:
        - context
      gen_kwargs:
        temperature: 0.7
        max_tokens: 2048
        n: 10
```
