### ISSUE TITLE
Enable activation of subset selection feature per dataset with related args from recipe.yaml

### ISSUE THREAD

**Issue by eshwarprasadS** [instructlab/sdg#528]
**Is your feature request related to a problem? Please describe.**

Currently, `datamixing.py` consumes only two fields from `recipe.yaml` pertaining to dataset mixing. These two fields are: `path` and `sampling_size`. It would be beneficial if we can make changes to `datamixing.py` to enable a more nuanced yaml that will contain which subsetting method to use, and its pertaining parameters as sub fields.

**Describe the solution you'd like**
We could easily enable subset selection from here as an option, if `datamixing.py` could parse a yaml that is designed like so (for example):
```
datasets:
  - path: instructlab_community.jsonl
    sampling_size: 1.0
    sampling_method: random
    sampling_params:
      seed: 42  # Optional: for reproducible random sampling

  - path: another_dataset.jsonl
    sampling_size: 0.8
    sampling_method: diversity
    sampling_params:
      num_folds: 5     # Optional: number of folds for diversity sampling
      epsilon: 0.1     # Optional: epsilon parameter for diversity calculation
```

**Additional context**
This would enable a minimal entry point to calling the Subset Selection feature. For the purposes of this issue, it could simply call to a dummy method, once the yaml is correctly parsed, and it is recognized as a call to Subset Selection.
