### ISSUE TITLE
ilab data generate fails with FIPS Mode enabled

### ISSUE THREAD

**Issue by AaronJaegerVA** [instructlab/sdg#587]
**Describe the bug**
`ilab data generate` fails when running on a FIPS-enabled host / cluster.

**To Reproduce**
1. Create qna.yaml
2. Validate with `ilab taxonomy diff`
3. Run `ilab data generate` on a FIPS-enabled host / cluster
1. See error

**Expected behavior**
Synthetic data is generated successfully.

**Command Used**
`ilab data generate`

**Device Info (please complete the following information):**
 - Hardware Specs: AWS G6 instance, 8 CPU / 24GB RAM
 - InstructLab Version: 
```
Platform:
  sys.version: 3.11.7 (main, Oct  9 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)]
  sys.platform: linux
  os.name: posix
  platform.release: 5.14.0-427.55.1.el9_4.x86_64
  platform.machine: x86_64
  platform.node: llm-test-0
  platform.python_version: 3.11.7
  os-release.ID: rhel
  os-release.VERSION_ID: 9.4
  os-release.PRETTY_NAME: Red Hat Enterprise Linux 9.4 (Plow)
  memory.total: 60.46 GB
  memory.available: 51.82 GB
  memory.used: 7.84 GB

InstructLab:
  instructlab.version: 0.24.3
  instructlab-dolomite.version: 0.2.0
  instructlab-eval.version: 0.5.1
  instructlab-quantize.version: 0.1.0
  instructlab-schema.version: 0.4.2
  instructlab-sdg.version: 0.7.2
  instructlab-training.version: 0.7.0

Torch:
  torch.version: 2.6.0+cu124
  torch.backends.cpu.capability: AVX2
  torch.version.cuda: 12.4
  torch.version.hip: None
  torch.cuda.available: True
  torch.backends.cuda.is_built: True
  torch.backends.mps.is_built: False
  torch.backends.mps.is_available: False
  torch.cuda.bf16: True
  torch.cuda.current.device: 0
  torch.cuda.0.name: NVIDIA L4
  torch.cuda.0.free: 1.0 GB
  torch.cuda.0.total: 22.0 GB
  torch.cuda.0.capability: 8.9 (see https://developer.nvidia.com/cuda-gpus#compute)

llama_cpp_python:
  llama_cpp_python.version: 0.3.6
  llama_cpp_python.supports_gpu_offload: False
``` 

**Additional context**
Running in Jupyter Notebook on top of OpenShift AI.
